#!/usr/bin/env bash
set -euo pipefail

echo "🚀 COINjecture Cloudflare HTTPS Deployment"
echo "=========================================="
echo ""

# Get S3 bucket IP address
echo "🔍 Getting S3 bucket IP address..."
S3_IP=$(nslookup coinjecture.com.s3-website.us-east-1.amazonaws.com | grep "Address:" | tail -1 | awk '{print $2}')
echo "   S3 IP: $S3_IP"
echo ""

echo "📋 Cloudflare Setup Instructions:"
echo ""
echo "1. 🌐 Go to https://cloudflare.com and sign up (free)"
echo "2. ➕ Click 'Add a Site' and enter: coinjecture.com"
echo "3. 🆓 Choose 'Free' plan"
echo "4. 🔄 Update nameservers at your domain registrar:"
echo "   (Cloudflare will show you 2 nameservers to use)"
echo ""
echo "5. 📝 Add these DNS records in Cloudflare:"
echo ""
echo "   Type: A"
echo "   Name: @"
echo "   Content: $S3_IP"
echo "   Proxy Status: 🟠 Proxied (ON)"
echo ""
echo "   Type: CNAME"
echo "   Name: www"
echo "   Content: coinjecture.com"
echo "   Proxy Status: 🟠 Proxied (ON)"
echo ""
echo "6. 🔐 Enable SSL/TLS settings:"
echo "   - Go to SSL/TLS → Overview"
echo "   - Set encryption mode to 'Flexible'"
echo "   - Go to SSL/TLS → Edge Certificates"
echo "   - Enable 'Always Use HTTPS'"
echo "   - Enable 'Automatic HTTPS Rewrites'"
echo ""
echo "7. ⏳ Wait 5-30 minutes for DNS propagation"
echo ""
echo "8. 🧪 Test HTTPS access:"
echo "   curl -I https://coinjecture.com"
echo "   curl -I https://www.coinjecture.com"
echo ""

echo "✅ Expected Results:"
echo "   - https://coinjecture.com (secure)"
echo "   - https://www.coinjecture.com (secure)"
echo "   - Free SSL certificate"
echo "   - Global CDN for faster loading"
echo "   - DDoS protection"
echo ""

echo "⏱️  Total Time: ~5 minutes setup + 5-30 minutes DNS propagation"
echo ""
echo "🎯 This is the FASTEST and EASIEST method for HTTPS!"
echo "   (Much faster than AWS CloudFront which takes 30+ minutes)"
